services:
  - type: web
    name: text-to-speech-translator
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
      php artisan storage:link
      npm ci
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: text-to-speech-translator
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: GOOGLE_TTS_API_KEY
        sync: false
      - key: LIBRETRANSLATE_API_KEY
        sync: false
